### ISSUE TITLE
Connect Django backend to Mongo Atlas cluster

### ISSUE THREAD

**Issue by Sheko1** [kalinpetrovbg/My-Wallet-Project#29]

**Comment by Sheko1** [comment]
Follow-up of issue #26

**Comment by KoliosterNikolayIliev** [comment]
Please read the points bellow. For me there is no reason for not using Djongo. If you all agree please let @Sheko1 close the issue and move it to done otherwise please share your concerns.

Reasons to consider using Djongo:

1.Djongo makes zero changes to the existing Django ORM framework
2.The only connector that let's you use Django with MongoDB without changing the Django ORM
3.It is not used 'instead' of pymongo but makes life easier.(requirements.txt down bellow)
4.Keeps all benefits of Django ORM
5.We could migrate to SQL database with very small ammount of changes. Let's hope not have such issue. :)
6.Under the hood Djongo translates SQL queries to Pymongo commands
7.It will be much easier for the team  


The only connector that let's you use Django with MongoDB without changing the Django ORM

Djongo repository -> https://github.com/nesdis/djongo
Documentation https://www.djongomapper.com/get-started/

Requirements.txt ->

sqlparse==0.2.4
pymongo>=3.2.0
django>=2.0,<=3.1.4

 # requirements.txt
 #
 # installs dependencies from ./setup.py, and the package itself,
 # in editable mode
 -e .

**Comment by DimoDimchev** [comment]
I agree with what @KoliosterNikolayIliev has said, but for now the issue should stay open because we have yet to connect the DB to our Django project.

When we successfully do that the issue can be closed.
